
TIME SERIES NORMALIZATION

Input:

1. 'a': numpy array contenente le time series
2. asse su sui calcolare media e deviazione standard
3. ddf: delta degree of freedom. =0 deviazione standard della popolazione


Output:

1. normalized array of time series

In [2]:
import math
import numpy as np
import multiprocessing
from numpy.random import randint
from numpy.linalg import norm, eigh
from numpy.fft import fft, ifft
from sklearn.base import ClusterMixin, BaseEstimator

In [48]:
def zscore(a, axis=0, ddof=0): #normalize always on the column axis
    a = np.asanyarray(a) #convert the input a in an array
    mns = a.mean(axis=axis) #compute the mean of the time series along the column axis (mean for each time instant)
    sstd = a.std(axis=axis, ddof=ddof) #compute the standard deviation of the array along the column axis (mean for each time instant)

    if axis and mns.ndim < a.ndim: #if the axis is specified and the n of dimensions of the mean array is < of the n of dimensions of the input array
        res = ((a - np.expand_dims(mns, axis=axis)) / #compute normalized data and expand the the mean and sd to match the dimension with the array a (the mean and std have 1 dimension less=
               np.expand_dims(sstd, axis=axis))
    else:
        res = (a - mns) / sstd #compute normalized data

    return np.nan_to_num(res)

   


In [49]:
#Example of multivariate array of time series:

#2 time series, with 3 time instants and 2 variables

a_multivariate = np.array([[[11, 1000], [25, 30], [350, 40]],
                           [[45, 0.2], [1, 0.111], [65, 70]]])

#compute the mean for each time instant
print(a_multivariate.mean(axis=0))

[[ 28.     500.1   ]
 [ 13.      15.0555]
 [207.5     55.    ]]


* 10 is the mean of variable 1 at time 0 /  4.5 is the mean of variable 2 at time 0
* 2 is the mean of variable 1 at time 1 /  6.5 is the mean of variable 2 at time 1
* ...

In [50]:
#we apply the zscore function

zscore_result = zscore(a_multivariate, axis=0)
print(zscore_result)


[[[-1.  1.]
  [ 1.  1.]
  [ 1. -1.]]

 [[ 1. -1.]
  [-1. -1.]
  [-1.  1.]]]


In [51]:
#Example of monovariate array of time series: 4 time series and 3 time instants
a_monovariate = np.array([[10, 12, 31],
              [4, 9, 10],
              [70, 81, 2],
              [12, 112, 12]])

#we apply the zscore function

zscore_result = zscore(a_monovariate, axis=0)
print(zscore_result)


[[-0.52393683 -0.93494794  1.62139887]
 [-0.74848119 -1.00253454 -0.35247801]
 [ 1.72150673  0.61954382 -1.10443111]
 [-0.44908871  1.31793866 -0.16448974]]


TIME SERIES SHIFTING