# K-shape algorithm

## Required Python Libraries

In [70]:
import math
import numpy as np
import os
import csv
import time
import multiprocessing
from numpy.random import randint
from numpy.linalg import norm, eigh
from numpy.fft import fft, ifft
from sklearn.base import ClusterMixin, BaseEstimator
from sklearn.metrics import rand_score, normalized_mutual_info_score, adjusted_rand_score

## Functions

### Z-score Function

Z-score is a mathematical approach to convert a "Generic" Random Variables to a Normal Random Variables. 

For more information about this approach: 
https://it.wikipedia.org/wiki/Standardizzazione_(statistica)

**Function Inputs**
1. ```a```: numpy array containing time-series values;
2. ```axis```: axis used to evaluate mean and standard deviation. For axis we intend rows or columns.
3. ```ddof```: Degrees of freedom correction in the calculation of the standard deviation. Default value equals to 0

**Function returned values**:
1. Normalized Time-Series

**Function Assumptions**:
1. ```axis = 0 ```: normalize always on column axis. This is true beacuse we want to normalize time instants values, to exlude possible outliers or errors

In [71]:
def zscore(a, axis=0, ddof=0):
    a = np.asanyarray(a) #convert the input a in an array
    mns = a.mean(axis=axis) #compute the mean of the time series along the column axis (mean for each time instant)
    sstd = a.std(axis=axis, ddof=ddof) #compute the standard deviation of the array along the column axis (mean for each time instant)

    ## If Condition-->
    ## If axis equals to row (axis = 1) and dimensions of mean array is lower than dimensions of time series array
    ## -----> calculate Z score expanding dimensions of mean and std array on row axis
    ## If axis equals to columns (axis = 0) or dimensions of mean array is equal to dimensions of time series array
    ## -----> calculate Z score as time-series array minus its mean, divided by standard deviation

    if axis and mns.ndim < a.ndim:
        res = ((a - np.expand_dims(mns, axis=axis)) / #compute normalized data and expand the the mean and sd to match the dimension with the array a (the mean and std have 1 dimension less=
               np.expand_dims(sstd, axis=axis))
    else:
        res = (a - mns) / sstd #compute normalized data

    ## nan_to_num method --> replace NaN values with 0 or large integer values for infinite values
    return np.nan_to_num(res)

   


### Roll_zeropad Function

```roll_zeropad``` is a custom function to shift time series values to the right. The number of positions required by the movement are evaluated with parameter ```shift```.
For each shift, a zero value is included in the time series.

**Function Inputs**
1. ```a```: numpy array containing time-series values;
2. ```shift```: Number of right movements required;
3. ```axis```: axis to consider for right movements.

**Function returned values**:
1. Shifted Time-Series

**Function Assumptions**:
1. ```axis = None ```: time series can be considered as a 1D array and not as a matrix

In [72]:
def roll_zeropad(a, shift, axis=None):
    # asanyarray method --> Convert the input to an ndarray, but pass ndarray subclasses through.
    a = np.asanyarray(a) # Ensure that the input is ndarrary data type

    # If no shift is required (shift = 0), it returns the original values of time series
    if shift == 0:
        return a

    # If axis parameter is not evaluated (axis = None)
    # ------> consider all elements of time series and not a specific dimensions, but this requires a reshape of data at the end
    # If axis is set
    # ------> extracted dimensions of a specific axis (rows or columns) and work on that
    if axis is None:
        n = a.size
        reshape = True
    else:
        n = a.shape[axis]
        reshape = False

    # zeros_like() method --> Return an array of zeros with the same shape and type as a given array.

    # If shift parameter is greater than size of the time series (but this requires that no axis are specified)
    # ------> it evaluates an array of 0 values with the same size of a
    if np.abs(shift) > n:
        res = np.zeros_like(a)
    # If shift parameter is lower than 0 (moving to the left)
    # ------> subtract the shift value to n size of the array
    # ------> extract the indices from 0 to (n-shift) values, considering a plain array (axis = None) or a specific dimensions
    # ------> generate a 0-valued array with size [0, (n-shift)]
    # ------> extract values from (n-shift) position to n position
    # ------> create an array with values in range [(n-shift),n] at the beginning and all 0 values after
    elif shift < 0:
        shift += n
        zeros = np.zeros_like(a.take(np.arange(n-shift), axis))
        res = np.concatenate((a.take(np.arange(n-shift, n), axis), zeros), axis)
    # If shift parameter is in the range [0, size of time series]
    # ------> extract values from (n-shift) position to n position
    # ------> generate a 0-valued array with size [(n-shift), n]
    # ------> extract the indices from 0 to (n-shift) values, considering a plain array (axis = None) or a specific dimensions
    # ------> create an array with 0 value at the beginning and then values in range [0, (n-shift)]
    else:
        zeros = np.zeros_like(a.take(np.arange(n-shift, n), axis))
        res = np.concatenate((zeros, a.take(np.arange(n-shift), axis)), axis)

    # If reshape is required
    # -----> change shape (row, column) of shifted array, considering shape of time series values
    if reshape:
        return res.reshape(a.shape)
    else:
        return res

### _ncc_c_3dim Function

```_ncc_c_3dim``` is a custom function to evaluate the optimal NCC value. NCC is a normalization of Cross Correlation value and it could be of 3 different types. Cross Correlation is a similiraty measures between 2 time series.

**Function Inputs**
1. ```data```: numpy array containing 2 time series to compare;

**Function returned values**:
1. Optimal Shift of Y

**Function Assumptions**:
1. ```None ```

In [73]:
def _ncc_c_3dim(data):
    x, y = data[0], data[1]
    #print(x)
    #print(y)
    den = norm(x, axis=(0,1)) * norm(y, axis=(0,1))

    if den < 1e-9:
        den = np.inf

    #print(x.shape)
    x_len = x.shape[0]
    fft_size = 1 << (2*x_len-1).bit_length()

    cc = ifft(fft(x, fft_size, axis=0) * np.conj(fft(y, fft_size, axis=0)), axis=0)
    cc = np.concatenate((cc[-(x_len-1):], cc[:x_len]), axis=0)

    return np.real(cc).sum(axis=-1) / den

In [74]:
def _sbd(x, y):
    ncc = _ncc_c_3dim([x, y])
    #print(type(ncc))
    idx = np.argmax(ncc)
    #print(ncc[idx])
    #yshift = 1. - ncc[idx]
    yshift = roll_zeropad(y, (idx + 1) - max(len(x), len(y)))

    return yshift

In [75]:
def collect_shift(data):
    x, cur_center = data[0], data[1]
    if np.all(cur_center==0):
        return x
    else:
        return _sbd(cur_center, x)

In [76]:
def _extract_shape(idx, x, j, cur_center):
    _a=[]
    for i in range(len(idx)):
        if idx[i] == j:
            _a.append(collect_shift([x[i], cur_center]))

    a = np.array(_a)
    
    if len(a) == 0:
        indices = np.random.choice(x.shape[0], 1)
        return np.squeeze(x[indices].copy())
        #return np.zeros((x.shape[1]))

    columns = a.shape[1]
    y = zscore(a, axis=1, ddof=1)

    s = np.dot(y[:, :, 0].transpose(), y[:, :, 0])
    p = np.empty((columns, columns))
    p.fill(1.0/columns)
    p = np.eye(columns) - p
    m = np.dot(np.dot(p, s), p)

    _, vec = eigh(m)
    centroid = vec[:, -1]

    finddistance1 = np.sum(np.linalg.norm(a - centroid.reshape((x.shape[1], 1)), axis=(1, 2)))
    finddistance2 = np.sum(np.linalg.norm(a + centroid.reshape((x.shape[1], 1)), axis=(1, 2)))

    if finddistance1 >= finddistance2:
        centroid *= -1

    return zscore(centroid, ddof=1)

In [77]:
def _kshape(x, k, centroid_init='zero', max_iter=100, n_jobs=1):
    m = x.shape[0]
    idx = randint(0, k, size=m)
    if centroid_init == 'zero':
        centroids = np.zeros((k, x.shape[1], x.shape[2]))
    elif centroid_init == 'random':
        indices = np.random.choice(x.shape[0], k)
        centroids = x[indices].copy()
    distances = np.empty((m, k))
    
    for it in range(max_iter):
        old_idx = idx

        for j in range(k):
            for d in range(x.shape[2]):
                centroids[j, :, d] = _extract_shape(idx, np.expand_dims(x[:, :, d], axis=2), j, np.expand_dims(centroids[j, :, d], axis=1))
                #centroids[j] = np.expand_dims(_extract_shape(idx, x, j, centroids[j]), axis=1)

        pool = multiprocessing.Pool(n_jobs)
        args = []
        for p in range(m):
            for q in range(k):
                args.append([x[p, :], centroids[q, :]])
        result = pool.map(_ncc_c_3dim, args)
        pool.close()
        r = 0
        for p in range(m):
            for q in range(k):
                distances[p, q] = 1 - result[r].max()
                r = r + 1

        idx = distances.argmin(1)
        if np.array_equal(old_idx, idx):
            break

    return idx, centroids

In [78]:
def kshape(x, k, centroid_init='zero', max_iter=100):
    idx, centroids = _kshape(np.array(x), k, centroid_init=centroid_init, max_iter=max_iter)
    clusters = []
    for i, centroid in enumerate(centroids):
        series = []
        for j, val in enumerate(idx):
            if i == val:
                series.append(j)
        clusters.append((centroid, series))

    return clusters

In [79]:
class KShapeClusteringCPU(ClusterMixin,BaseEstimator):
    labels_= None
    centroids_ = None

    def __init__(self,n_clusters, centroid_init='zero', max_iter=100, n_jobs=None):
        self.n_clusters = n_clusters
        self.centroid_init = centroid_init
        self.max_iter = max_iter
        if n_jobs is None:
            self.n_jobs=1
        elif n_jobs == -1:
            self.n_jobs = multiprocessing.cpu_count()
        else:
            self.n_jobs=n_jobs
        


    def fit(self,X,y=None):
        clusters = self._fit(X,self.n_clusters, self.centroid_init, self.max_iter,self.n_jobs)
        self.labels_ = np.zeros(X.shape[0])
        self.centroids_ =np.zeros((self.n_clusters, X.shape[1], X.shape[2]))
        for i in range(self.n_clusters):
            self.labels_[clusters[i][1]] = i
            self.centroids_[i]=clusters[i][0]
        return self

    def predict(self, X):
        labels, _ = self._predict(X,self.centroids_)
        return labels
        
    
    def _predict(self,x, centroids):
        m = x.shape[0]
        idx = randint(0, self.n_clusters, size=m)
        distances = np.empty((m, self.n_clusters))
        

    
        pool = multiprocessing.Pool(self.n_jobs)
        args = []
        for p in range(m):
            for q in range(self.n_clusters):
                args.append([x[p, :], centroids[q, :]])
        result = pool.map(_ncc_c_3dim, args)
        pool.close()
        r = 0
        for p in range(m):
            for q in range(self.n_clusters):
                distances[p, q] = 1 - result[r].max()
                r = r + 1
    
        idx = distances.argmin(1)

        return idx, centroids
    
    
    def _fit(self,x, k, centroid_init='zero', max_iter=100,n_jobs=1):
        idx, centroids = _kshape(np.array(x), k, centroid_init=centroid_init, max_iter=max_iter, n_jobs=n_jobs)
        clusters = []
        for i, centroid in enumerate(centroids):
            series = []
            for j, val in enumerate(idx):
                if i == val:
                    series.append(j)
            clusters.append((centroid, series))
    
        return clusters

## Correlated Functions

In [88]:
class ClusterDataLoader:
    def __init__(self, dataset_path):
        self.path = dataset_path

    def load(self, sub_dataset_name):
        ts, labels = [], []
        for mode in ['_TRAIN']:
            with open(os.path.join(self.path, sub_dataset_name, sub_dataset_name + mode)) as csv_file:
                lines = csv.reader(csv_file, delimiter=',')
                for line in lines:
                    ts.append([float(x) for x in line[1:]])
                    labels.append(int(line[0])-1)

        if min(labels) == 1:
            labels = labels - 1
        if min(labels) == -1:
            labels = labels + 1

        return np.array(ts), np.array(labels), int(len(set(labels)))

In [89]:
DATASET_PATH = 'dataset/univariate_example/'
DATASET_NAME = 'Crop'

dataloder = ClusterDataLoader(DATASET_PATH)

In [90]:
ts, labels, num_clusters = dataloder.load(DATASET_NAME)

In [91]:
print(ts.shape)

(7200, 46)


In [92]:
print(labels.shape)

(7200,)


In [93]:
print(num_clusters)

24


In [95]:
start_time = time.time()

ksc = KShapeClusteringCPU(n_clusters=num_clusters,max_iter=2,n_jobs=-1)
ksc.fit(np.expand_dims(ts, axis=2))
print(f'Iteration {i}: time: {time.time() - start_time}')

In [86]:
cpu_times = []
for i in range(5):
    start_time = time.time()

    ksc = KShapeClusteringCPU(n_clusters=num_clusters,max_iter=100,n_jobs=-1)
    ksc.fit(np.expand_dims(ts, axis=2))
    print(f'Iteration {i}: time: {time.time() - start_time}')
    
    cpu_times.append(time.time() - start_time)

<class 'numpy.ndarray'>
0.9344663112339117
<class 'numpy.ndarray'>
0.7757189265766148
<class 'numpy.ndarray'>
0.6885728074356906
<class 'numpy.ndarray'>
0.8866391778351008
<class 'numpy.ndarray'>
0.9127484950694612
<class 'numpy.ndarray'>
0.8470040986436749
<class 'numpy.ndarray'>
0.8380813430647005
<class 'numpy.ndarray'>
0.8215086871279595
<class 'numpy.ndarray'>
0.8256872650259696
<class 'numpy.ndarray'>
0.3462834334143692
<class 'numpy.ndarray'>
0.8608931413294404
<class 'numpy.ndarray'>
0.8682056663866283
<class 'numpy.ndarray'>
0.5852320479409175
<class 'numpy.ndarray'>
0.6985070752332145
<class 'numpy.ndarray'>
0.358706313755427
<class 'numpy.ndarray'>
0.20873211048536108
<class 'numpy.ndarray'>
0.40616490837677244
<class 'numpy.ndarray'>
0.35999777562845986
<class 'numpy.ndarray'>
0.5229463229127078
<class 'numpy.ndarray'>
0.5961858134119974
<class 'numpy.ndarray'>
0.5543627120737503
<class 'numpy.ndarray'>
0.7692498383876822
<class 'numpy.ndarray'>
0.6723888321399312
<class 'n

KeyboardInterrupt: 

## Code Flow

## In Depth Examples

### Monovariate Time Series

Monovariate time-series can be represented as a matrix NxM with:
- N (rows) as the number of time-series. Each row represent a time series which can be connected to a specific date 
- M (columns) as time instants considered for each time series. Each time instants respects a frequency of analysis 

In [ ]:
#Example of monovariate array of time series: 4 time series and 3 time instants
##
a_monovariate = np.array([[10, 12, 31],
              [4, 9, 10],
              [70, 81, 2],
              [12, 112, 12]])

### Multivariate Time Series

Multivariate time-series can be represented as a matrix NxM with:
- N (rows) as the number of time-series. Each row represent a time series which can be connected to a specific date 
- M (columns) as time instants considered for each time series. Each time instants respects a frequency of analysis 

The main difference with monovariate time-series is that each cell of the matrix is an array of values. The number of elements of the array can be considered as the number of variables involved, in addition to timestamp

In [ ]:
#Example of multivariate array of time series:

#2 time series, with 3 time instants and 2 variables

a_multivariate = np.array([[[11, 1000], [25, 30], [350, 40]],
                           [[45, 0.2], [1, 0.111], [65, 70]],
                           [[17, 59], [11, 14], [45, 87]]])

#compute the mean for each time instant
print("Mean\n-----------")
print(a_multivariate.mean(axis=0))
print("Std\n-----------")
print(a_multivariate.std(axis=0))

Mean
-----------
[[ 24.33333333 353.06666667]
 [ 12.33333333  14.70366667]
 [153.33333333  65.66666667]]
Std
-----------
[[ 14.81740718 458.080352  ]
 [  9.84321537  12.21227362]
 [139.30382463  19.43078886]]


The output can be explained as:
- Cell 0,0 ==> mean (or std) of first elements of first time instant;
- Cell 0,1 ==> mean (or std) of second elements of first time instant;
- Cell 1,0 ==> mean (or std) of first elements of second time instant;
....

So the output is a matrix Nx(M-1)

### Multivariate Time Series - zScore

In [ ]:
#we apply the zscore function
zscore_result = zscore(a_multivariate)
print(zscore_result)

[[[-0.89984254  1.41227042]
  [ 1.28684238  1.25253772]
  [ 1.41178225 -1.32092767]]

 [[ 1.39475594 -0.77031609]
  [-1.15138528 -1.19491809]
  [-0.63410559  0.22301376]]

 [[-0.4949134  -0.64195433]
  [-0.13545709 -0.05761963]
  [-0.77767666  1.09791391]]]


### Monovariate Time Series - zScore

In [ ]:
#we apply the zscore function
zscore_result = zscore(a_monovariate, axis=0)
print(zscore_result)


[[-0.52393683 -0.93494794  1.62139887]
 [-0.74848119 -1.00253454 -0.35247801]
 [ 1.72150673  0.61954382 -1.10443111]
 [-0.44908871  1.31793866 -0.16448974]]


### Monovariate Time Series - Shifting

In [ ]:
print(a_monovariate)

[[ 10  12  31]
 [  4   9  10]
 [ 70  81   2]
 [ 12 112  12]]


In [ ]:
a_monovariate_shifted = roll_zeropad(a_monovariate, 1)
print(a_monovariate_shifted)

[[  0  10  12]
 [ 31   4   9]
 [ 10  70  81]
 [  2  12 112]]


Evaluating parameter ```shift``` to 1, the function shifts time series to the right of one position

In [ ]:
a_monovariate_shifted = roll_zeropad(a_monovariate, -1)
print(a_monovariate_shifted)

[[ 12  31   4]
 [  9  10  70]
 [ 81   2  12]
 [112  12   0]]


Evaluating parameter ```shift``` to -1, the function shifts time series to the left of one position

In [ ]:
a_monovariate_shifted = roll_zeropad(a_monovariate, 5)
print(a_monovariate_shifted)

[[ 0  0  0]
 [ 0  0 10]
 [12 31  4]
 [ 9 10 70]]


In [ ]:
a_monovariate_shifted = roll_zeropad(a_monovariate, -3)
print(a_monovariate_shifted)

[[  4   9  10]
 [ 70  81   2]
 [ 12 112  12]
 [  0   0   0]]


### Multivariate Time Series - Shifting

In [ ]:
print(a_multivariate)

[[[1.10e+01 1.00e+03]
  [2.50e+01 3.00e+01]
  [3.50e+02 4.00e+01]]

 [[4.50e+01 2.00e-01]
  [1.00e+00 1.11e-01]
  [6.50e+01 7.00e+01]]

 [[1.70e+01 5.90e+01]
  [1.10e+01 1.40e+01]
  [4.50e+01 8.70e+01]]]


In [ ]:
a_multivariate_shifted = roll_zeropad(a_multivariate, 1)
print(a_multivariate_shifted)

[[[0.00e+00 1.10e+01]
  [1.00e+03 2.50e+01]
  [3.00e+01 3.50e+02]]

 [[4.00e+01 4.50e+01]
  [2.00e-01 1.00e+00]
  [1.11e-01 6.50e+01]]

 [[7.00e+01 1.70e+01]
  [5.90e+01 1.10e+01]
  [1.40e+01 4.50e+01]]]


The shifting works across the same row. Considering that each element of row has an array of values, which indexes means different variables to analyze (temp, humidity, etc), this can generate misunderstanding data because the operation changes the variable associated to data value

### Monovariate Time Series - NCCc

In [ ]:
x = np.array([[2,5]])
y = np.array([[2,5]])

nccc = _ncc_c_3dim([x,y])

print(nccc)

[[2 5]]
[[2 5]]
(1, 2)
[1. 0. 1.]


In [ ]:
sbd = _sbd(x,y)

print(f"SBD: {sbd}")

<class 'numpy.ndarray'>
1.0000000000000002
SBD: [[2 5]]


### FFT

In [ ]:
x_len = 300
xlen_trans = 2*x_len-1
print(xlen_trans)

599


In [ ]:
print(xlen_trans.bit_length())

10


In [ ]:
print (1 << xlen_trans.bit_length())

1024


In [ ]:
print(2 ** 11)

2048


In [ ]:
print(fft([2,5],))

[ 7.        +0.j          5.53553391-3.53553391j  2.        -5.j
 -1.53553391-3.53553391j -3.        +0.j         -1.53553391+3.53553391j
  2.        +5.j          5.53553391+3.53553391j]


In [ ]:
print(np.zeros((2, 2, 3)))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
